### ISSUE TITLE
UniverseNet using experience

### ISSUE THREAD

**Issue by HBioquant** [shinya7y/UniverseNet#22]
A pretty work and I have carefully read your paper! There is a question: 
we use your UniverseNet on our benchmark for a different task and do lots of works. So far, we have found your network was fifty-fifty with Faster RCNN in the Detectron2. So, I'd like to ask you what are the significant improvements in your model that allow the network to be "universal" and have better performance than Faster RCNN or other networks.

**Comment by shinya7y** [comment]
Thank you for reading.

> fifty-fifty with Faster RCNN in the Detectron2.

Which config did you use?
1x or 3x? `MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)`? fine-tuning from COCO?
In any case, performance gaps between multi-stage and single-stage detectors depend on datasets.

> what are the significant improvements

As shown in Table 6, ATSS achieves 2.3 higher mCAP than RetinaNet.
As shown in Table 12(f), many methods improve COCO AP by 1.6+. Although we haven't conduct ablation studies on other datasets due to limited resources, Res2Net, DCN, and multi-scale training will have high priority.
