### ISSUE TITLE
time and data_time

### ISSUE THREAD

**Issue by swapnil-saha** [shinya7y/UniverseNet#6]
what do time and data_time in train log json file indicate?

**Comment by shinya7y** [comment]
| Method | Backbone | GPU | time | data_time |
| :---: | :---: | :---: | :---: | :---: |
| UniverseNet | R2-50 | T4 * 4 | 2.2383 | 0.0174 |
| UniverseNet | R2-50 | V100 * 8 | 0.6193 | 0.0120 |
| UniverseNet+GFL | R2-50 | T4 * 4 | 2.2040 | 0.0148 |
| UniverseNet+GFL | R2-101 | T4 * 4 | 3.2678 | 0.0143 |
| UniverseNet 20.08 | R2-50 | T4 * 4 | 1.2291 | 0.0168 |

I calculated the mean (without `include_outliers`) of the second epoch, because the log files are fragmented due to resume.
